version: '3.8'
services:
    postgres:
        image: postgres
        restart: always
        environment:
            - POSTGRES_PASSWORD=postgres
    
    api:
      build: 
        dockerfile: Dockerfile
        context: "./backend"
      ports:
          - "8000:8000"
      depends_on:
        - postgres
<<<<<<< HEAD
      env_file:
        - backend/.env
=======
      environment:
          - POSTGRES_PASSWORD=postgres
>>>>>>> e435cb8f048a98b3de6d3f30a64c4a0039f09c95
    
    client:
      stdin_open: true
      build:
        dockerfile: Dockerfile
        context: "./client"
      ports:
        - "3000:3000"
      # volumes:
      #   - /app/node_modules
      #   - ./client:/app
      environment:
        - CHOKIDAR_USEPOLLING=true