version: '3.8'
services:
    postgres:
        image: postgres
        restart: always
        environment:
            - POSTGRES_PASSWORD=postgres
    
    server:
        build: ./server
        ports:
            - "8000:8000"
        depends_on:
          - postgres
        environment:
            - POSTGRES_PASSWORD=postgres